"""
TENSION TRADING DESK — CRT PLAIN (same-TF)
==========================================
Separate from the hybrid M5-sweep engine (3C Model in 3c_model.py).

Locked research survivors, plain only:
  CRT 1H→15m
  CRT 1H→5m
  CRT 4H→30m
  CRT 4H→15m

CRT PLAIN ONLY:
- No OHP / OLP
- No Premium / Discount
- No Order Blocks / FVG / IFVG
- No extra key-level, trend, session, momentum, VWAP, or SMC filters

Base:
  C1 = prior closed HTF candle
  C2 = next HTF candle sweeps one side and closes back inside
  Entry confirmation = first LTF close back inside C1 range after C2
  Entry = swept-side C1 boundary
  TP1 = 50% of C1
  TP2 = opposite side
  SL = beyond C2 extreme
  No auto BE

TELEGRAM TRADE LIFECYCLE:
  Original signal:
      TRADE ACTIVE

  First target:
      TP1 HIT — HEADING TO TP2
      Same original Telegram message is edited.

  Final target:
      TP2 HIT
      FINAL VERDICT: WIN
      Same original Telegram message is edited.

  Stop:
      SL HIT
      FINAL VERDICT: LOSS
      Same original Telegram message is edited.

IMPORTANT:
- No separate WIN/LOSS broadcast is generated by CRT Plain.
- Completed trades are still written to shared outcomes.json.
- 3c_model.py remains untouched.
- 3C Model remains a separate strategy.

PRODUCTION MAINTENANCE:
- No Saturday/Sunday trade generation.
- Signal timestamps: 🇳🇬 WAT in 12-hour AM/PM + 🌐 UTC in 24-hour time.
- Each signal carries its UTC-defined forex session.
- Each completed signal gets an explicit WIN / LOSS verdict.
- TP1 is a milestone, not a final verdict.
- Weekly/monthly/yearly scorecards roll up completed CRT Plain outcomes.
- Session performance is included in scorecards.
"""

import os
import json
from datetime import datetime, timedelta, timezone
import importlib

import numpy as np
import pandas as pd


desk = importlib.import_module("3c_model")


STATE_FILE = "last_alert_state_crt_plain.json"
STATE_VERSION = 2

MIN_RR = 1.5

WEEK_CLOSE_UTC_HOUR = 21

PAIRS = desk.PAIRS


STREAMS = {
    "CRT 1H→15m": ("1h", "15min"),
    "CRT 1H→5m": ("1h", "5min"),
    "CRT 4H→30m": ("4h", "30min"),
    "CRT 4H→15m": ("4h", "15min"),
}


# ============================================================
# STATE
# ============================================================

def _default_state():
    return {
        "version": STATE_VERSION,
        "last_alert_keys": {},
        "pending": [],
        "last_weekly_report": "",
        "last_monthly_report": "",
        "last_yearly_report": "",
    }


def load_state():
    default = _default_state()

    if not os.path.exists(STATE_FILE):
        return default

    try:
        with open(STATE_FILE, "r") as f:
            state = json.load(f)

        if state.get("version") != STATE_VERSION:
            return default

        state.setdefault("last_alert_keys", {})
        state.setdefault("pending", [])
        state.setdefault("last_weekly_report", "")
        state.setdefault("last_monthly_report", "")
        state.setdefault("last_yearly_report", "")

        return state

    except Exception as e:
        print("CRT plain state load error:", e)
        return default


def save_state(state):
    tmp = STATE_FILE + ".tmp"

    with open(tmp, "w") as f:
        json.dump(state, f, indent=2)

    os.replace(tmp, STATE_FILE)


# ============================================================
# TIME / SESSION
# ============================================================

def _parse_utc(value):
    try:
        ts = pd.Timestamp(value)

        if ts.tzinfo is None:
            return ts.tz_localize("UTC")

        return ts.tz_convert("UTC")

    except Exception:
        return None


def _format_dual_time(value, include_date=True):
    """
    Required display:

    🇳🇬 WAT = UTC+1, 12-hour AM/PM
    🌐 UTC = 24-hour
    """

    ts = _parse_utc(value)

    if ts is None:
        return "🇳🇬 n/a WAT · 🌐 n/a UTC"

    wat = ts + pd.Timedelta(hours=1)

    wat_text = wat.strftime("%I:%M %p").lstrip("0")
    utc_text = ts.strftime("%H:%M")

    if include_date:
        date_text = wat.strftime("%d %b %Y")

        return (
            f"🇳🇬 {wat_text} WAT · "
            f"🌐 {utc_text} UTC · {date_text}"
        )

    return (
        f"🇳🇬 {wat_text} WAT · "
        f"🌐 {utc_text} UTC"
    )


def _session_for_utc(value):
    """
    Fixed UTC session buckets for deterministic reporting.

    Asia:
        00:00–07:59 UTC

    London:
        08:00–12:59 UTC

    New York:
        13:00–20:59 UTC
    """

    ts = _parse_utc(value)

    if ts is None:
        return "Unknown"

    hour = ts.hour

    if 0 <= hour < 8:
        return "Asia"

    if 8 <= hour < 13:
        return "London"

    return "New York"


def _session_window_text():
    return (
        "Asia 00–07 UTC · "
        "London 08–12 UTC · "
        "New York 13–20 UTC"
    )


# ============================================================
# CRT LOGIC — LOCKED
# ============================================================

def find_setup(htf, pip):
    """
    Latest closed C2 only.

    C2 must sweep C1 and close back inside.
    """

    if htf is None or len(htf) < 5:
        return None

    c2 = htf.iloc[-2]
    c1 = htf.iloc[-3]

    crh = float(c1["high"])
    crl = float(c1["low"])

    mid = (crh + crl) / 2.0

    if crh - crl < 5 * pip:
        return None

    # Bullish CRT
    if (
        float(c2["low"]) < crl
        and crl < float(c2["close"]) < crh
    ):
        return {
            "crh": crh,
            "crl": crl,
            "mid": mid,
            "extreme": float(c2["low"]),
            "direction": 1,
            "c2_time": str(c2["datetime"]),
        }

    # Bearish CRT
    if (
        float(c2["high"]) > crh
        and crl < float(c2["close"]) < crh
    ):
        return {
            "crh": crh,
            "crl": crl,
            "mid": mid,
            "extreme": float(c2["high"]),
            "direction": -1,
            "c2_time": str(c2["datetime"]),
        }

    return None


def ltf_entry(ltf, setup):
    """
    First LTF close back inside C1 after C2.

    The first qualifying LTF close is used.
    """

    if ltf is None or len(ltf) < 10:
        return None

    c2_time = pd.Timestamp(setup["c2_time"])

    after = ltf[
        ltf["datetime"] > c2_time
    ]

    if after.empty:
        return None

    crh = setup["crh"]
    crl = setup["crl"]

    for _, row in after.iterrows():

        close = float(row["close"])

        if crl < close < crh:
            return row

    return None


def analyze(
    stream_label,
    htf_name,
    ltf_name,
    htf,
    ltf,
    pair,
    pip,
):
    setup = find_setup(
        htf,
        pip,
    )

    if setup is None:
        return None

    bar = ltf_entry(
        ltf,
        setup,
    )

    if bar is None:
        return None

    if (
        "atr" in bar
        and not pd.isna(bar["atr"])
    ):
        atr = float(bar["atr"])
    else:
        atr = 0.0

    buf = max(
        1.5 * pip,
        0.25 * atr
        if atr > 0
        else 1.5 * pip,
    )

    direction = setup["direction"]

    if direction == 1:

        entry = setup["crl"]

        stop = (
            setup["extreme"]
            - buf
        )

        tp1 = setup["mid"]
        tp2 = setup["crh"]

    else:

        entry = setup["crh"]

        stop = (
            setup["extreme"]
            + buf
        )

        tp1 = setup["mid"]
        tp2 = setup["crl"]

    risk = abs(
        entry - stop
    )

    if risk <= 0:
        return None

    rr1 = abs(
        tp1 - entry
    ) / risk

    rr2 = abs(
        tp2 - entry
    ) / risk

    if rr1 < MIN_RR:
        return None

    candle_time = str(
        bar["datetime"]
    )

    return {
        "stream": stream_label,
        "pair": pair,
        "direction": direction,
        "side": (
            "BUY"
            if direction == 1
            else "SELL"
        ),
        "entry": float(entry),
        "stop": float(stop),
        "tp1": float(tp1),
        "tp2": float(tp2),
        "rr1": float(rr1),
        "rr2": float(rr2),
        "risk_pips": float(
            risk / pip
        ),
        "crh": setup["crh"],
        "crl": setup["crl"],
        "mid": setup["mid"],
        "candle_time": candle_time,
        "session": _session_for_utc(
            candle_time
        ),
        "candle_key": (
            f"{stream_label}|"
            f"{pair}|"
            f"{setup['c2_time']}|"
            f"{direction}"
        ),
        "c1_tf": htf_name,
        "ltf": ltf_name,
    }


# ============================================================
# INITIAL SIGNAL MESSAGE
# ============================================================

def build_signal_message(sig):

    emoji = (
        "🟢"
        if sig["direction"] == 1
        else "🔴"
    )

    session = (
        sig.get("session")
        or _session_for_utc(
            sig["candle_time"]
        )
    )

    return (
        f"<b>TENSION TRADING DESK</b>\n"
        f"════════════════════\n"
        f"<b>{sig['stream']}</b> · plain\n"
        f"────────────────────\n\n"

        f"{emoji} <b>{sig['side']} "
        f"{sig['pair']}</b>\n\n"

        f"C1 TF: <b>{sig['c1_tf'].upper()}</b> · "
        f"Entry: <b>{sig['ltf']}</b>\n"

        f"Session: <b>{session}</b>\n"

        f"Sweep: same TF as C1, "
        f"close back inside\n\n"

        f"C1 High <b>{sig['crh']:.5f}</b>\n"
        f"C1 Mid  <b>{sig['mid']:.5f}</b>\n"
        f"C1 Low  <b>{sig['crl']:.5f}</b>\n\n"

        f"Entry <b>{sig['entry']:.5f}</b>\n"

        f"SL    <b>{sig['stop']:.5f}</b> "
        f"({sig['risk_pips']:.1f} pips)\n"

        f"TP1   <b>{sig['tp1']:.5f}</b> "
        f"(mid · {sig['rr1']:.2f}R measured)\n"

        f"TP2   <b>{sig['tp2']:.5f}</b> "
        f"(opposite · {sig['rr2']:.2f}R measured)\n\n"

        f"Signal time: <b>"
        f"{_format_dual_time(sig['candle_time'])}"
        f"</b>\n\n"

        f"🚀 <b>TRADE ACTIVE</b>\n"
        f"Status: <b>ACTIVE</b>\n\n"

        f"<a href=\""
        f"{desk.tradingview_url(sig['pair'])}"
        f"\">Open {sig['pair']} on TradingView</a>\n\n"

        f"Built on Data.\n"
        f"Driven by Discipline."
    )


# ============================================================
# TELEGRAM EDIT MESSAGES
# ============================================================

def _tp1_status_message(trade):
    """
    TP1 milestone.

    IMPORTANT:
    This edits the ORIGINAL signal.

    It does NOT resolve the trade.
    """

    direction_emoji = (
        "🟢"
        if int(trade["direction"]) == 1
        else "🔴"
    )

    session = (
        trade.get("session")
        or _session_for_utc(
            trade.get("candle_time")
        )
    )

    return (
        f"<b>TENSION TRADING DESK</b>\n"
        f"════════════════════\n"
        f"<b>{trade.get('stream', '')}</b> · plain\n"
        f"────────────────────\n\n"

        f"{direction_emoji} "
        f"<b>{trade.get('side', '')} "
        f"{trade.get('pair', '')}</b>\n\n"

        f"Session: <b>{session}</b>\n\n"

        f"🎯 <b>TP1 HIT — HEADING TO TP2</b>\n\n"

        f"<b>TRADE STATUS</b>\n"
        f"Status: <b>TP1 HIT</b>\n"
        f"Trade remains <b>ACTIVE</b>.\n\n"

        f"<b>LEVELS</b>\n"

        f"Entry: <b>"
        f"{float(trade['entry']):.5f}"
        f"</b>\n"

        f"SL: <b>"
        f"{float(trade['stop']):.5f}"
        f"</b>\n"

        f"TP1: <b>"
        f"{float(trade['tp1']):.5f}"
        f"</b> ✓ HIT\n"

        f"TP2: <b>"
        f"{float(trade['tp2']):.5f}"
        f"</b>\n\n"

        f"Measured TP1: <b>"
        f"{float(trade.get('rr1', 0)):.2f}R"
        f"</b>\n"

        f"Measured TP2: <b>"
        f"{float(trade.get('rr2', 0)):.2f}R"
        f"</b>\n\n"

        f"No automatic BE is applied.\n\n"

        f"TP1 time: <b>"
        f"{_format_dual_time(trade.get('tp1_time'))}"
        f"</b>\n\n"

        f"Built on Data.\n"
        f"Driven by Discipline."
    )


def _outcome_status_message(
    trade,
    status,
    candle_time,
    result_r=None,
):
    """
    FINAL status of the ORIGINAL Telegram signal.

    WIN:
        TP2 hit.

    LOSS:
        SL hit.

    This function is used only for editing the original
    signal. It does NOT broadcast another message.
    """

    direction_emoji = (
        "🟢"
        if int(trade["direction"]) == 1
        else "🔴"
    )

    session = (
        trade.get("session")
        or _session_for_utc(
            trade.get("candle_time")
        )
    )

    status_upper = str(
        status
    ).upper()

    tp1_hit = bool(
        trade.get(
            "tp1_hit",
            False,
        )
    )

    if status_upper == "WIN":

        headline = (
            "🏆 <b>FINAL VERDICT: WIN</b>"
        )

        detail = (
            "🎯 <b>TP2 HIT</b>\n"
            "Trade completed at TP2."
        )

    elif status_upper == "LOSS":

        headline = (
            "❌ <b>FINAL VERDICT: LOSS</b>"
        )

        detail = (
            "🛑 <b>SL HIT</b>\n"
            "Trade completed at the stop loss."
        )

    else:

        headline = (
            f"ℹ️ <b>{status_upper}</b>"
        )

        detail = (
            "Trade status updated."
        )

    if result_r is not None:

        result_line = (
            f"Result: "
            f"<b>{float(result_r):+.2f}R</b>"
        )

    else:

        result_line = ""

    if tp1_hit:

        tp1_line = (
            "🎯 <b>TP1 HIT</b> — milestone reached"
        )

    else:

        tp1_line = (
            "🎯 <b>TP1</b> — not reached"
        )

    return (
        f"<b>TENSION TRADING DESK</b>\n"
        f"════════════════════\n"
        f"<b>{trade.get('stream', '')}</b> · plain\n"
        f"────────────────────\n\n"

        f"{direction_emoji} "
        f"<b>{trade.get('side', '')} "
        f"{trade.get('pair', '')}</b>\n"

        f"Session: <b>{session}</b>\n\n"

        f"{headline}\n"
        f"{detail}\n\n"

        f"<b>TRADE PROGRESS</b>\n"
        f"{tp1_line}\n"

        f"🎯 TP2: <b>"
        f"{float(trade['tp2']):.5f}"
        f"</b>\n\n"

        f"{result_line}\n\n"

        f"<b>LEVELS</b>\n"

        f"Entry: <b>"
        f"{float(trade['entry']):.5f}"
        f"</b>\n"

        f"SL: <b>"
        f"{float(trade['stop']):.5f}"
        f"</b>\n"

        f"TP1: <b>"
        f"{float(trade['tp1']):.5f}"
        f"</b>\n"

        f"TP2: <b>"
        f"{float(trade['tp2']):.5f}"
        f"</b>\n\n"

        f"Outcome time: <b>"
        f"{_format_dual_time(candle_time)}"
        f"</b>\n\n"

        f"Built on Data.\n"
        f"Driven by Discipline."
    )


# ============================================================
# OUTCOME LOGGING
# ============================================================

def _log_completed_trade(
    trade,
    status,
    result_r,
    exit_time,
):
    """
    Write the completed CRT Plain trade to the shared
    outcomes.json through 3c_model.py.

    IMPORTANT:
    This records the outcome only.

    It does NOT send Telegram messages.
    """

    record = {
        "stream": trade.get(
            "stream"
        ),
        "pair": trade.get(
            "pair"
        ),
        "side": trade.get(
            "side"
        ),
        "status": status,
        "result_r": (
            float(result_r)
            if result_r is not None
            else None
        ),
        "exit_time": exit_time,

        "entry": trade.get(
            "entry"
        ),
        "stop": trade.get(
            "stop"
        ),
        "tp1": trade.get(
            "tp1"
        ),
        "tp2": trade.get(
            "tp2"
        ),
        "rr1": trade.get(
            "rr1"
        ),
        "rr2": trade.get(
            "rr2"
        ),

        "candle_time": trade.get(
            "candle_time"
        ),

        "signal_time": trade.get(
            "signal_time",
            trade.get("candle_time"),
        ),

        "session": trade.get(
            "session"
        ),

        "tp1_hit": bool(
            trade.get(
                "tp1_hit",
                False,
            )
        ),

        "tp1_time": trade.get(
            "tp1_time"
        ),

        "tp2_hit": (
            status == "WIN"
        ),
    }

    try:

        desk.log_outcome(
            record
        )

    except Exception as e:

        print(
            "CRT Plain outcome log error:",
            e,
        )


# ============================================================
# PENDING TRADE MANAGEMENT
# ============================================================

def check_pending(
    state,
    pair,
    ltf,
):
    """
    Manage an already-issued CRT Plain signal.

    TELEGRAM FLOW:

        ORIGINAL SIGNAL
              ↓
        TP1 HIT — HEADING TO TP2
              ↓
        TP2 HIT → FINAL VERDICT: WIN

    OR:

        ORIGINAL SIGNAL
              ↓
        SL HIT → FINAL VERDICT: LOSS

    The SAME original Telegram message is edited.

    No separate WIN/LOSS broadcast is made.
    """

    if not state["pending"] or ltf is None:
        return

    remaining = []

    latest = len(ltf) - 1

    primary = (
        str(desk.CHAT_ID)
        if desk.CHAT_ID
        else None
    )

    for trade in state["pending"]:

        if trade.get("pair") != pair:

            remaining.append(
                trade
            )

            continue

        try:

            entry_time = pd.Timestamp(
                trade["candle_time"]
            )

            matches = np.where(
                ltf["datetime"].values
                >= entry_time.to_datetime64()
            )[0]

        except Exception:

            remaining.append(
                trade
            )

            continue

        if len(matches) == 0:

            remaining.append(
                trade
            )

            continue

        signal_index = int(
            matches[0]
        )

        last_checked = int(
            trade.get(
                "last_checked_index",
                signal_index,
            )
        )

        start = max(
            signal_index + 1,
            last_checked + 1,
        )

        direction = int(
            trade["direction"]
        )

        stop = float(
            trade["stop"]
        )

        tp1 = float(
            trade["tp1"]
        )

        tp2 = float(
            trade["tp2"]
        )

        edit_chat = (
            trade.get(
                "edit_chat_id"
            )
            or primary
        )

        closed = False

        for j in range(
            start,
            latest + 1,
        ):

            high = float(
                ltf["high"].iloc[j]
            )

            low = float(
                ltf["low"].iloc[j]
            )

            candle_time = str(
                ltf["datetime"].iloc[j]
            )

            trade[
                "last_checked_index"
            ] = j

            if direction == 1:

                hit_sl = (
                    low <= stop
                )

                hit_tp2 = (
                    high >= tp2
                )

                hit_tp1 = (
                    high >= tp1
                )

            else:

                hit_sl = (
                    high >= stop
                )

                hit_tp2 = (
                    low <= tp2
                )

                hit_tp1 = (
                    low <= tp1
                )

            # =================================================
            # SL
            # =================================================
            #
            # Candle-level priority is preserved:
            # SL is checked before TP2 because OHLC data alone
            # cannot establish which level was touched first
            # when both are inside the same candle.
            #

            if hit_sl:

                message = (
                    _outcome_status_message(
                        trade,
                        "LOSS",
                        candle_time,
                        -1.0,
                    )
                )

                edited = desk.edit_telegram(
                    trade.get(
                        "message_id"
                    ),
                    message,
                    edit_chat,
                )

                if not edited:

                    print(
                        "CRT Plain LOSS "
                        "message edit failed:",
                        trade.get("pair"),
                        trade.get("stream"),
                    )

                _log_completed_trade(
                    trade,
                    "LOSS",
                    -1.0,
                    candle_time,
                )

                closed = True

                break

            # =================================================
            # TP1
            # =================================================
            #
            # TP1 does NOT close the trade.
            #

            if (
                hit_tp1
                and not trade.get(
                    "tp1_hit",
                    False,
                )
            ):

                trade[
                    "tp1_hit"
                ] = True

                trade[
                    "tp1_time"
                ] = candle_time

                edited = desk.edit_telegram(
                    trade.get(
                        "message_id"
                    ),
                    _tp1_status_message(
                        trade
                    ),
                    edit_chat,
                )

                if not edited:

                    print(
                        "CRT Plain TP1 "
                        "message edit failed:",
                        trade.get("pair"),
                        trade.get("stream"),
                    )

            # =================================================
            # TP2
            # =================================================
            #
            # TP2 = FINAL WIN.
            #

            if hit_tp2:

                # If the same candle reaches TP1 and TP2,
                # record TP1 as reached before finalizing.
                if not trade.get(
                    "tp1_hit",
                    False,
                ):

                    trade[
                        "tp1_hit"
                    ] = True

                    trade[
                        "tp1_time"
                    ] = candle_time

                rr2 = float(
                    trade.get(
                        "rr2",
                        0.0,
                    )
                )

                message = (
                    _outcome_status_message(
                        trade,
                        "WIN",
                        candle_time,
                        rr2,
                    )
                )

                edited = desk.edit_telegram(
                    trade.get(
                        "message_id"
                    ),
                    message,
                    edit_chat,
                )

                if not edited:

                    print(
                        "CRT Plain WIN "
                        "message edit failed:",
                        trade.get("pair"),
                        trade.get("stream"),
                    )

                _log_completed_trade(
                    trade,
                    "WIN",
                    rr2,
                    candle_time,
                )

                closed = True

                break

        if not closed:

            remaining.append(
                trade
            )

    state["pending"] = remaining


# ============================================================
# REPORT PERIOD HELPERS
# ============================================================

def _week_close_for_date(date_obj):
    """
    Friday 21:00 UTC for the ISO week containing date_obj.
    """

    monday = (
        date_obj
        - timedelta(
            days=date_obj.weekday()
        )
    )

    friday = (
        monday
        + timedelta(days=4)
    )

    return datetime(
        friday.year,
        friday.month,
        friday.day,
        WEEK_CLOSE_UTC_HOUR,
        0,
        0,
        tzinfo=timezone.utc,
    )


def _previous_week_window(now_utc):

    current_monday = (
        now_utc.date()
        - timedelta(
            days=now_utc.weekday()
        )
    )

    previous_monday = (
        current_monday
        - timedelta(days=7)
    )

    week_start = datetime(
        previous_monday.year,
        previous_monday.month,
        previous_monday.day,
        0,
        0,
        0,
        tzinfo=timezone.utc,
    )

    week_close = _week_close_for_date(
        previous_monday
    )

    iso = previous_monday.isocalendar()

    week_key = (
        f"{iso.year}-W{iso.week:02d}"
    )

    return (
        week_start,
        week_close,
        week_key,
    )


def _previous_month_window(now_utc):

    first_current = datetime(
        now_utc.year,
        now_utc.month,
        1,
        0,
        0,
        0,
        tzinfo=timezone.utc,
    )

    previous_last = (
        first_current
        - timedelta(seconds=1)
    )

    start = datetime(
        previous_last.year,
        previous_last.month,
        1,
        0,
        0,
        0,
        tzinfo=timezone.utc,
    )

    close = datetime(
        previous_last.year,
        previous_last.month,
        previous_last.day,
        23,
        59,
        59,
        tzinfo=timezone.utc,
    )

    key = (
        f"{start.year}-"
        f"{start.month:02d}"
    )

    return (
        start,
        close,
        key,
    )


def _previous_year_window(now_utc):

    year = now_utc.year - 1

    start = datetime(
        year,
        1,
        1,
        0,
        0,
        0,
        tzinfo=timezone.utc,
    )

    close = datetime(
        year,
        12,
        31,
        23,
        59,
        59,
        tzinfo=timezone.utc,
    )

    return (
        start,
        close,
        str(year),
    )


# ============================================================
# OUTCOMES
# ============================================================

def _is_crt_plain_record(record):

    stream = str(
        record.get(
            "stream",
            "",
        )
    )

    return stream.startswith(
        "CRT "
    )


def _load_crt_outcomes():

    try:

        rows = desk.load_outcomes()

        if not isinstance(
            rows,
            list,
        ):
            return []

        return [
            row
            for row in rows
            if _is_crt_plain_record(
                row
            )
        ]

    except Exception as e:

        print(
            "CRT outcomes load error:",
            e,
        )

        return []


def _record_signal_time(row):

    for key in (
        "signal_time",
        "candle_time",
        "entry_time",
        "time",
    ):

        value = row.get(key)

        if value:

            ts = _parse_utc(
                value
            )

            if ts is not None:
                return ts

    return None


def _record_session(row):

    stored = row.get(
        "session"
    )

    if stored:
        return str(
            stored
        )

    return _session_for_utc(
        _record_signal_time(row)
    )


# ============================================================
# PERFORMANCE METRICS
# ============================================================

def _performance_metrics(
    rows,
    start,
    close,
):

    selected = []

    for row in rows:

        exit_ts = _parse_utc(
            row.get("exit_time")
            or row.get("resolved_time")
            or row.get("close_time")
        )

        if exit_ts is None:
            continue

        if (
            start
            <= exit_ts
            <= close
        ):

            selected.append(
                (
                    row,
                    exit_ts,
                )
            )

    total = len(
        selected
    )

    wins = sum(
        1
        for row, _
        in selected
        if str(
            row.get(
                "status",
                "",
            )
        ).upper()
        == "WIN"
    )

    losses = sum(
        1
        for row, _
        in selected
        if str(
            row.get(
                "status",
                "",
            )
        ).upper()
        == "LOSS"
    )

    time_exits = sum(
        1
        for row, _
        in selected
        if str(
            row.get(
                "status",
                "",
            )
        ).upper()
        == "TIME EXIT"
    )

    rs = []
    winning_rs = []
    losing_rs = []

    for row, _ in selected:

        try:

            r = float(
                row.get(
                    "result_r"
                )
            )

        except Exception:

            continue

        rs.append(r)

        if r > 0:

            winning_rs.append(
                r
            )

        elif r < 0:

            losing_rs.append(
                r
            )

    total_r = sum(
        rs
    )

    avg_r = (
        total_r / len(rs)
        if rs
        else 0.0
    )

    avg_win_r = (
        sum(winning_rs)
        / len(winning_rs)
        if winning_rs
        else 0.0
    )

    avg_loss_r = (
        sum(losing_rs)
        / len(losing_rs)
        if losing_rs
        else 0.0
    )

    gross_profit = sum(
        r
        for r in rs
        if r > 0
    )

    gross_loss_abs = abs(
        sum(
            r
            for r in rs
            if r < 0
        )
    )

    if gross_loss_abs > 0:

        profit_factor = (
            gross_profit
            / gross_loss_abs
        )

    elif gross_profit > 0:

        profit_factor = float(
            "inf"
        )

    else:

        profit_factor = 0.0

    win_rate = (
        wins / total * 100
        if total
        else 0.0
    )

    best_r = (
        max(rs)
        if rs
        else 0.0
    )

    worst_r = (
        min(rs)
        if rs
        else 0.0
    )

    tp1_touches = sum(
        1
        for row, _
        in selected
        if bool(
            row.get(
                "tp1_hit",
                False,
            )
        )
    )

    tp2_wins = sum(
        1
        for row, _
        in selected
        if str(
            row.get(
                "status",
                "",
            )
        ).upper()
        == "WIN"
    )

    pairs = {}
    streams = {}
    sessions = {}
    session_r = {}
    session_trades = {}

    for row, _ in selected:

        pair = str(
            row.get(
                "pair",
                "Unknown",
            )
        )

        stream = str(
            row.get(
                "stream",
                "Unknown",
            )
        )

        session = _record_session(
            row
        )

        pairs[pair] = (
            pairs.get(
                pair,
                0,
            )
            + 1
        )

        streams[stream] = (
            streams.get(
                stream,
                0,
            )
            + 1
        )

        sessions[session] = (
            sessions.get(
                session,
                0,
            )
            + 1
        )

        try:

            r = float(
                row.get(
                    "result_r"
                )
            )

        except Exception:

            r = 0.0

        session_r[session] = (
            session_r.get(
                session,
                0.0,
            )
            + r
        )

        session_trades[session] = (
            session_trades.get(
                session,
                0,
            )
            + 1
        )

    return {
        "total": total,
        "wins": wins,
        "losses": losses,
        "time_exits": time_exits,
        "win_rate": win_rate,
        "total_r": total_r,
        "avg_r": avg_r,
        "avg_win_r": avg_win_r,
        "avg_loss_r": avg_loss_r,
        "profit_factor": profit_factor,
        "best_r": best_r,
        "worst_r": worst_r,
        "tp1_touches": tp1_touches,
        "tp2_wins": tp2_wins,
        "pairs": pairs,
        "streams": streams,
        "sessions": sessions,
        "session_r": session_r,
        "session_trades": session_trades,
    }


def _performance_verdict(m):

    if m["total"] == 0:

        return (
            "⚪ NO TRADES",
            "No completed CRT Plain "
            "trades in this period.",
        )

    if (
        m["total_r"] >= 5
        and m["win_rate"] >= 60
    ):

        return (
            "🟢 VERY NICE PERIOD",
            "Strong positive recorded R "
            "with a solid recorded win rate.",
        )

    if (
        m["total_r"] >= 2
        and m["win_rate"] >= 50
    ):

        return (
            "🟢 GOOD PERIOD",
            "Positive recorded R with at "
            "least half of trades winning.",
        )

    if m["total_r"] > 0:

        return (
            "🟡 POSITIVE PERIOD",
            "The completed sample finished "
            "above zero R.",
        )

    if m["total_r"] == 0:

        return (
            "🟡 MIXED PERIOD",
            "The completed sample finished "
            "around breakeven.",
        )

    if m["total_r"] <= -5:

        return (
            "🔴 VERY BAD PERIOD",
            "Large negative recorded R "
            "in the completed sample.",
        )

    return (
        "🔴 BAD PERIOD",
        "The completed sample finished "
        "below zero R.",
    )


def _format_distribution(data):

    if not data:
        return "• None"

    return "\n".join(
        f"• {name}: {count}"
        for name, count
        in sorted(
            data.items(),
            key=lambda item: (
                -item[1],
                item[0],
            ),
        )
    )


def _format_session_performance(
    metrics
):

    if not metrics[
        "session_trades"
    ]:

        return "• None"

    rows = []

    for (
        session,
        trades,
    ) in sorted(
        metrics[
            "session_trades"
        ].items(),
        key=lambda item: (
            -item[1],
            item[0],
        ),
    ):

        total_r = metrics[
            "session_r"
        ].get(
            session,
            0.0,
        )

        rows.append(
            f"• {session}: "
            f"{trades} trades | "
            f"{total_r:+.2f}R"
        )

    return "\n".join(
        rows
    )


# ============================================================
# REPORT BUILDERS
# ============================================================

def _build_report(
    title,
    period_key,
    start,
    close,
    metrics,
):

    verdict, explanation = (
        _performance_verdict(
            metrics
        )
    )

    pf = metrics[
        "profit_factor"
    ]

    pf_text = (
        "∞"
        if pf == float("inf")
        else f"{pf:.2f}"
    )

    if metrics["total"]:

        result_line = (
            f"{metrics['wins']}W / "
            f"{metrics['losses']}L"
        )

        if metrics["time_exits"]:

            result_line += (
                f" / "
                f"{metrics['time_exits']} TIME"
            )

    else:

        result_line = "0W / 0L"

    return (
        f"<b>TENSION TRADING DESK</b>\n"
        f"════════════════════\n"
        f"📊 <b>CRT PLAIN — "
        f"{title}</b>\n"
        f"<b>{period_key}</b>\n"
        f"────────────────────\n\n"

        f"📅 <b>Trading window</b>\n"
        f"{_format_dual_time(start)}\n"
        f"→ {_format_dual_time(close)}\n\n"

        f"🏁 <b>PERIOD VERDICT</b>\n"
        f"{verdict}\n"
        f"{explanation}\n\n"

        f"<b>PERFORMANCE</b>\n"

        f"Trades: <b>"
        f"{metrics['total']}</b>\n"

        f"Record: <b>"
        f"{result_line}</b>\n"

        f"Win Rate: <b>"
        f"{metrics['win_rate']:.1f}%</b>\n"

        f"Total R: <b>"
        f"{metrics['total_r']:+.2f}R</b>\n"

        f"Average R: <b>"
        f"{metrics['avg_r']:+.2f}R</b>\n"

        f"Avg Win: <b>"
        f"+{metrics['avg_win_r']:.2f}R</b>\n"

        f"Avg Loss: <b>"
        f"{metrics['avg_loss_r']:.2f}R</b>\n"

        f"Profit Factor: <b>"
        f"{pf_text}</b>\n"

        f"Best Trade: <b>"
        f"{metrics['best_r']:+.2f}R</b>\n"

        f"Worst Trade: <b>"
        f"{metrics['worst_r']:+.2f}R</b>\n\n"

        f"<b>TRADE EVENTS</b>\n"

        f"TP2 Wins: <b>"
        f"{metrics['tp2_wins']}</b>\n"

        f"TP1 Touches Logged: <b>"
        f"{metrics['tp1_touches']}</b>\n"

        f"Time Exits: <b>"
        f"{metrics['time_exits']}</b>\n\n"

        f"<b>PAIRS</b>\n"
        f"{_format_distribution(metrics['pairs'])}\n\n"

        f"<b>STREAMS</b>\n"
        f"{_format_distribution(metrics['streams'])}\n\n"

        f"<b>SESSION PERFORMANCE</b>\n"
        f"{_format_session_performance(metrics)}\n\n"

        f"<i>{_session_window_text()}</i>\n\n"

        f"🇳🇬 WAT · 🌐 UTC\n"
        f"Built on Data.\n"
        f"Driven by Discipline."
    )


# ============================================================
# REPORT SENDING
# ============================================================

def _telegram_available():

    try:

        if desk.CHAT_ID:
            return True

        subscribers = (
            desk.load_subscribers()
        )

        return bool(
            subscribers
        )

    except Exception:

        return False


def _send_once(
    state,
    state_key,
    period_key,
    report,
    label,
):

    if state.get(
        state_key
    ) == period_key:

        return False

    if not _telegram_available():

        print(
            f"CRT {label} report "
            f"not sent — no Telegram "
            f"subscribers."
        )

        return False

    try:

        message_id = desk.broadcast(
            report
        )

    except Exception as e:

        print(
            f"CRT {label} report "
            f"broadcast error:",
            e,
        )

        return False

    if not message_id:

        print(
            f"CRT {label} report "
            f"not confirmed sent."
        )

        return False

    state[
        state_key
    ] = period_key

    print(
        f"CRT {label} report sent: "
        f"{period_key}"
    )

    return True


def maybe_send_weekly_report(
    state,
    now_utc=None,
):

    """
    Weekly report:

    Released on Saturday only.

    Covers:
      Previous Monday 00:00 UTC
      through Friday 21:00 UTC
    """

    now_utc = (
        now_utc
        or datetime.now(
            timezone.utc
        )
    )

    if now_utc.weekday() != 5:
        return

    (
        start,
        close,
        week_key,
    ) = _previous_week_window(
        now_utc
    )

    if now_utc < close:
        return

    rows = _load_crt_outcomes()

    metrics = _performance_metrics(
        rows,
        start,
        close,
    )

    report = _build_report(
        "WEEKLY PERFORMANCE OVERVIEW",
        week_key,
        start,
        close,
        metrics,
    )

    _send_once(
        state,
        "last_weekly_report",
        week_key,
        report,
        "weekly",
    )


def maybe_send_monthly_report(
    state,
    now_utc=None,
):

    """
    Monthly report:

    Released on Saturday.

    Covers the previous complete
    calendar month.
    """

    now_utc = (
        now_utc
        or datetime.now(
            timezone.utc
        )
    )

    if now_utc.weekday() != 5:
        return

    (
        start,
        close,
        month_key,
    ) = _previous_month_window(
        now_utc
    )

    if now_utc <= close:
        return

    rows = _load_crt_outcomes()

    metrics = _performance_metrics(
        rows,
        start,
        close,
    )

    report = _build_report(
        "MONTHLY PERFORMANCE OVERVIEW",
        month_key,
        start,
        close,
        metrics,
    )

    _send_once(
        state,
        "last_monthly_report",
        month_key,
        report,
        "monthly",
    )


def maybe_send_yearly_report(
    state,
    now_utc=None,
):

    """
    Yearly report:

    Released on Saturday.

    Covers the previous complete
    calendar year.
    """

    now_utc = (
        now_utc
        or datetime.now(
            timezone.utc
        )
    )

    if now_utc.weekday() != 5:
        return

    (
        start,
        close,
        year_key,
    ) = _previous_year_window(
        now_utc
    )

    if now_utc <= close:
        return

    rows = _load_crt_outcomes()

    metrics = _performance_metrics(
        rows,
        start,
        close,
    )

    report = _build_report(
        "YEARLY PERFORMANCE OVERVIEW",
        year_key,
        start,
        close,
        metrics,
    )

    _send_once(
        state,
        "last_yearly_report",
        year_key,
        report,
        "yearly",
    )


# ============================================================
# MAIN
# ============================================================

def main():

    print("=" * 70)

    print(
        "TENSION TRADING DESK — "
        "CRT PLAIN (same-TF)"
    )

    print(
        "1H→15m | 1H→5m | "
        "4H→30m | 4H→15m"
    )

    print(
        "No Premium/Discount | "
        "No extra confluence"
    )

    print(
        "Telegram lifecycle: "
        "ACTIVE → TP1 → TP2/WIN or SL/LOSS"
    )

    print("=" * 70)

    if not desk.TWELVE_DATA_KEY:

        print(
            "Missing TWELVE_DATA_KEY"
        )

        return

    now_utc = datetime.now(
        timezone.utc
    )

    state = load_state()

    # ========================================================
    # WEEKEND GUARD
    # ========================================================

    if now_utc.weekday() >= 5:

        maybe_send_weekly_report(
            state,
            now_utc,
        )

        maybe_send_monthly_report(
            state,
            now_utc,
        )

        maybe_send_yearly_report(
            state,
            now_utc,
        )

        save_state(
            state
        )

        print(
            "\nCRT PLAIN WEEKEND MODE | "
            "No new trades | pending:",
            len(
                state["pending"]
            ),
        )

        return

    cache = {}

    for pair, cfg in PAIRS.items():

        pip = cfg["pip"]

        print(
            f"\n--- {pair} ---"
        )

        needed = set()

        for (
            htf_name,
            ltf_name,
        ) in STREAMS.values():

            needed.add(
                htf_name
            )

            needed.add(
                ltf_name
            )

        frames = {}

        ok = True

        for tf in needed:

            key = (
                pair,
                tf,
            )

            if key not in cache:

                cache[key] = desk.fetch(
                    pair,
                    tf,
                    (
                        400
                        if tf != "5min"
                        else 500
                    ),
                )

            frames[tf] = cache[key]

            if frames[tf] is None:

                ok = False

        if not ok:

            print(
                "  data failed"
            )

            continue

        for tf in frames:

            frames[tf] = (
                desk.add_atr(
                    frames[tf]
                )
            )

        for (
            stream_label,
            (
                htf_name,
                ltf_name,
            ),
        ) in STREAMS.items():

            ltf = frames[
                ltf_name
            ]

            # Check existing trades FIRST.
            #
            # This allows a previous signal to move:
            # ACTIVE → TP1 → TP2/SL.
            #

            check_pending(
                state,
                pair,
                ltf,
            )

            sig = analyze(
                stream_label,
                htf_name,
                ltf_name,
                frames[htf_name],
                ltf,
                pair,
                pip,
            )

            if sig is None:

                print(
                    f"  {stream_label}: "
                    f"no setup"
                )

                continue

            key = sig[
                "candle_key"
            ]

            state_key = (
                f"{stream_label}:"
                f"{pair}"
            )

            if (
                state[
                    "last_alert_keys"
                ].get(
                    state_key
                )
                == key
            ):

                print(
                    f"  {stream_label}: "
                    f"already alerted"
                )

                continue

            dup = any(
                t.get("pair") == pair
                and t.get(
                    "stream"
                ) == stream_label
                and t.get(
                    "status"
                ) == "ACTIVE"
                for t in state[
                    "pending"
                ]
            )

            if dup:

                print(
                    f"  {stream_label}: "
                    f"active trade open"
                )

                continue

            # =================================================
            # SEND ORIGINAL SIGNAL
            # =================================================

            message_id = (
                desk.broadcast(
                    build_signal_message(
                        sig
                    )
                )
            )

            if not message_id:

                print(
                    f"  {stream_label}: "
                    f"signal NOT "
                    f"confirmed sent"
                )

                continue

            print(
                f"  {stream_label}: "
                f"signal -> "
                f"{sig['side']} | "
                f"{sig['session']} | "
                f"{sig['risk_pips']:.1f} pips"
            )

            state[
                "last_alert_keys"
            ][
                state_key
            ] = key

            # =================================================
            # STORE PENDING TRADE
            # =================================================

            state[
                "pending"
            ].append(
                {
                    "stream": (
                        stream_label
                    ),

                    "pair": pair,

                    # Telegram message that will be
                    # edited through the entire lifecycle.
                    "message_id": (
                        message_id
                    ),

                    "edit_chat_id": (
                        str(
                            desk.CHAT_ID
                        )
                        if desk.CHAT_ID
                        else None
                    ),

                    "direction": (
                        sig["direction"]
                    ),

                    "side": (
                        sig["side"]
                    ),

                    "entry": (
                        sig["entry"]
                    ),

                    "stop": (
                        sig["stop"]
                    ),

                    "tp1": (
                        sig["tp1"]
                    ),

                    "tp2": (
                        sig["tp2"]
                    ),

                    "rr1": (
                        sig["rr1"]
                    ),

                    "rr2": (
                        sig["rr2"]
                    ),

                    "risk_pips": (
                        sig["risk_pips"]
                    ),

                    "candle_time": (
                        sig["candle_time"]
                    ),

                    "candle_key": key,

                    "session": (
                        sig["session"]
                    ),

                    "signal_time": (
                        sig["candle_time"]
                    ),

                    "status": "ACTIVE",

                    "tp1_hit": False,

                    "tp1_time": None,

                    "last_checked_index": (
                        len(ltf) - 1
                    ),
                }
            )

    # ========================================================
    # REPORTS
    # ========================================================

    maybe_send_weekly_report(
        state,
        now_utc,
    )

    maybe_send_monthly_report(
        state,
        now_utc,
    )

    maybe_send_yearly_report(
        state,
        now_utc,
    )

    save_state(
        state
    )

    print(
        "\nCRT PLAIN SCAN COMPLETE | "
        "pending:",
        len(
            state["pending"]
        ),
    )


if __name__ == "__main__":
    main()
